//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> Kategoriid { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Kdv { get; set; }
        public string Description { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
